version: '3.4'

services:
  revhautapp:
    image: revhautapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - 3000:3000
    depends_on:
      - postgresdb
    # env_file:
    #   - ./.env'
  postgresdb:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5422:5432
    volumes:
      - 'postgresdb:/var/lib/postgresql/data'
  redis:
    container_name: redis-cache
    image: redis
    ports:
      - '6379:6379'
volumes:
  postgresdb:
